import { getSession } from "next-auth/react";
import Head from "next/head";
import Header from "../components/Header";
import LeftSidebar from "../components/Sidebar/LeftSidebar";
import RightSidebar from "../components/Sidebar/RightSidebar.js";
import Login from "../components/Login";
import Feed from "../components/Feeds/Feed";

export default function Home({ session }) {
  if (!session) return <Login />;

  return (
    <div>
      <Head>
        <title>Project Share</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className="flex bg-gray-100">
        {/* Left sidebar */}
        <LeftSidebar />
        {/* feed */}
        <Feed />
        {/* Right */}
        <RightSidebar />
      </main>
    </div>
  );
}

export async function getServerSideProps(context) {
  const session = await getSession(context);
  return {
    props: {
      session,
    },
  };
}
